apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer #если не будет, будет обычный тип дефолтный cluster ip
  loadBalancerIP: 192.168.99.102
  ports: #какие порты должны быть открыты. Бывает несовпадение портов с докером. почитать: https://habr.com/ru/company/flant/blog/484954/
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
    - port: 22
      name: ssh
      targetPort: 22

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers: #откуда контейнеры будут собираться
        - name: nginx-container
          image: nginx-image
          imagePullPolicy: Never
          ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          - containerPort: 22
            name: ssh
# не факт что и эти порты и EXPOSE должны быть и то и то.
# возможно оставить что-то одно