apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb
spec:
  selector:
    app: ftps
  loadBalancerIP: 192.168.99.221
  type: LoadBalancer
  ports:
  - port: 20
    name: data
  - port: 21
    name: control
  - port: 21000
    name: pass

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps-container
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftps-data
        - containerPort: 21
          name: ftps-control
        - containerPort: 21000
          name: ftps-pass
